"""Cria tabela de usuarios

Revision ID: 9cb6b83a6096
Revises: c91e4c74db0d
Create Date: 2026-06-01 08:14:25.212526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb6b83a6096'
down_revision: Union[str, Sequence[str], None] = 'c91e4c74db0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
